# Generated by Django 4.0.3 on 2022-04-29 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('valor', models.IntegerField()),
                ('descicao', models.TextField(blank=True)),
                ('imagem', models.ImageField(upload_to='')),
            ],
            options={
                'verbose_name_plural': 'Livros',
            },
        ),
    ]
