# Generated by Django 4.0.3 on 2022-04-30 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livros',
            name='nota',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='livros',
            name='porcentagem',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='livros',
            name='quantidade_avaliacoes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='livros',
            name='quantidade_estrelas',
            field=models.FloatField(default=0),
        ),
    ]
