# Generated by Django 4.0.3 on 2022-05-02 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ebook', '0004_vote'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carrinho',
            old_name='livros',
            new_name='livro',
        ),
    ]
